---
Name: simple_template_caching
---
Page:
  extensions:
    - Sunnysideup\SimpleTemplateCaching\Extensions\PageExtension

PageController:
  extensions:
    - Sunnysideup\SimpleTemplateCaching\Extensions\PageControllerExtension
    - Sunnysideup\SimpleTemplateCaching\Extensions\ControllerExtension

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Sunnysideup\SimpleTemplateCaching\Extensions\AddLastEditedIndex

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Sunnysideup\SimpleTemplateCaching\Extensions\SimpleTemplateCachingSiteConfigExtension

SilverStripe\ORM\DataObject:
  extensions:
    - Sunnysideup\SimpleTemplateCaching\Extensions\DataObjectExtension

Sunnysideup\SimpleTemplateCaching\Extensions\DataObjectExtension:
  excluded_classes_for_caching:
    - SilverStripe\Security\Group
    - SilverStripe\Security\GroupTag
    - SilverStripe\Security\LoginAttempt
    - SilverStripe\Security\Member
    - SilverStripe\Security\MemberPassword
    - SilverStripe\Security\Permission
    - SilverStripe\Security\RememberLoginHash
    - SilverStripe\UserForms\Model\Submission\SubmittedForm
    - SilverStripe\UserForms\Model\Submission\SubmittedFormField
    - SilverStripe\UserForms\Model\Submission\SubmittedFileField
    - SilverStripe\Versioned\ChangeSet
    - SilverStripe\Versioned\ChangeSetItem
    - SilverStripe\SessionManager\Models\LoginSession
---
Name: corecache_extended
After:
  - '#corecache'
---
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.cacheblock:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: 'cacheblock'
      defaultLifetime: 864000 # 10 days!
